### PR TITLE
Change the definitions for the DB timestamps columns so they update…

### PR DESCRIPTION
**Pull request by antcodes**
…automatically

### CODE REVIEW

**Comment by calebporzio** [comment]
It looks like there is some random indentation going on here. Is that right?

**Comment by antcodes** [comment]
Hmm, weird.  That doesn't show up in Sublime; it's all indented properly and evenly.  But if I highlight the code, I can see that some of the old code used a mix of tabs and spaces for indentation.  I've now removed all the spaces, so all these blocks now use only tabs, and the indentation is even, both in Sublime and on github.

**Comment by calebporzio** [comment]
Ok, thats odd. We should all be using 4 spaces instead of tabs. That's part of our style guide. sublime setting: ""tab_size": 4,"

**Comment by antcodes** [comment]
I already have that setting, in Default/Preferences.sublime-settings, it says "tab_size": 4

I don't have a tab_size setting in User/Preferences.sublime-settings

**Comment by calebporzio** [comment]
Oh, ok, then everything should be good. I'll pull it in: thanks!

**Pull request merged**
